version: "3.9"

services:
  databse:
    container_name: database
    image: postgres:16-alpine
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
